### PR TITLE
Initial documentation

### PR DESCRIPTION
**Pull request by grahamu**

### CODE REVIEW

**Comment by grahamu** [comment]
@brosner this documentation is ready for review. I suggest you view starting with the [index](https://github.com/grahamu/pinax-api/blob/documentation/docs/index.md) and then click through to the various pages.

Please prioritize errors over content, and content over style. Thanks!

**Comment by brosner** [comment]
I have read through the documentation and I am not sure if I've ever read documentation so well written. I honestly didn't find any critical errors. You've described everything _exactly_ how I see it being described. This is seriously well done. Overall, I think this is ready for inclusion as-is and we can fix any minor issues as we see them.

**Comment by paltman** [comment]
+1

Awesome work!

**Comment by jtauber** [comment]
w00t!

**Pull request merged**
